<a href="https://colab.research.google.com/github/SnehaJainM/All-Flowers/blob/main/Numpy_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy

In [ ]:
numpy_array = numpy.array([33,19,2,3,4])

In [ ]:
numpy_array

array([33, 19,  2,  3,  4])

*Numpy arrays*


*   homogenous collection
*   if heterogrenous is passed it converts into the datatype in the given array
*   List to List  operations cannot be performed multiplying two lists for ex






In [ ]:
numpy_array1 = numpy.array([33,19,2,3,4,'hello'])

In [ ]:
numpy_array1
#all ele are converted to string

array(['33', '19', '2', '3', '4', 'hello'], dtype='<U21')

In [ ]:
numpy_array2 = numpy.array([33,19,2,3,4.5,'hello'])
numpy_array2
#all ele are converted to str

array(['33', '19', '2', '3', '4.5', 'hello'], dtype='<U32')

In [ ]:
numpy_array2 = numpy.array([33,19,2,3,4.5])
numpy_array2
#all ele are converted to float

array([33. , 19. ,  2. ,  3. ,  4.5])

In [ ]:
# numpy_array2 = numpy.array([33,19,2,[3,5]])
numpy_array2
# gives an error because single elements cannot be converted into lists

array([33. , 19. ,  2. ,  3. ,  4.5])

In [ ]:
numpy_array2 = numpy.array([33,19,2,3,{8,9,'what'}])
numpy_array2
numpy_dict_array=numpy.array(('yay',2,3,{4,5}))
numpy_dict_array
#sets and dictionaries are considered as objects thus no type conversions are done.
# when you try to access to objects the last object is returned by the control. so use a print() if you want to run both and display them.

array(['yay', 2, 3, {4, 5}], dtype=object)

In [ ]:
numpy_complex_arr =numpy.array((1+4j,2,3,4,5))
numpy_complex_arr
#complex conversions are done.

array([1.+4.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

08.02.2025
Pandas

Series()
DataFrame()


In [2]:
import pandas

In [ ]:
pandas_series = pandas.Series([33,19,2,3,4])
pandas_series

0    33
1    19
2     2
3     3
4     4
dtype: int64

In [ ]:
pandas_series=pandas.Series([33,19,2,3,4],index=['a','b','c','d','e'])
pandas_series

a    33
b    19
c     2
d     3
e     4
dtype: int64

In [ ]:
pandas_series = pandas.Series([.89,19,2,3,4],index=['a','b','c','d','e'],dtype=float)
pandas_series

a     0.89
b    19.00
c     2.00
d     3.00
e     4.00
dtype: float64

In [ ]:
pandas_series = pandas.Series([.89,19,2,3,4],index=['a','b','c','d','e'],name='Numbers')
pandas_series

a     0.89
b    19.00
c     2.00
d     3.00
e     4.00
Name: Numbers, dtype: float64

In [ ]:
pandas_series = pandas.Series([.89,19,2,3,4],index=['a','b','c','d','e'],name='Numbers')
pandas_series

a     0.89
b    19.00
c     2.00
d     3.00
e     4.00
Name: Numbers, dtype: float64

In [ ]:
dataframes = pandas.DataFrame()
print(dataframes)

Empty DataFrame
Columns: []
Index: []


In [ ]:

dataframes = pandas.DataFrame(['Shinchan','Doraemon','Kitretsu'],index=[7,2,3],columns=['Cartoons'])
# dataframes.columns = ['Cartoons']
dataframes

Cartoons
7  Shinchan
2  Doraemon
3  Kitretsu

In [ ]:
dataframes = pandas.DataFrame([['Shinchan',678,],['Doraemon',688,],['Kitretsu',987]],columns=['Cartoons','Channel'])
dataframes

Cartoons  Channel
0  Shinchan      678
1  Doraemon      688
2  Kitretsu      987

**2.02.25**


1.   df_array.columns
2.   df_array['col'].unique()
3.   df_array['colname'].value_counts()
4.   df_array.loc[row_index,'colname']






In [ ]:
df_array = pandas.DataFrame([['Sneha',9087764532],['Nikhil',9087543212],['Badshah',8900065432]],index=['a','b','c'],columns=['Name','ID'])
df_array

Name          ID
a    Sneha  9087764532
b   Nikhil  9087543212
c  Badshah  8900065432

In [ ]:
df_array.columns


Index(['Name', 'ID'], dtype='object')

In [ ]:
df_array = pandas.DataFrame([['Sneha',None,'Tshirt',1800],
 ['Nikhil',9087543212,'Airpods',2500],['Brunda',9087764532,'Pastel Palette',None],['Nikhil',9087543212,'Airpods',2500],['Badshah',8900065432,'HP Laptop',49000]],columns=['Name','ID','ProductName','Price'])
df_array.isnull()
df_array.notnull()

Name     ID  ProductName  Price
0  True  False         True   True
1  True   True         True   True
2  True   True         True  False
3  True   True         True   True
4  True   True         True   True

In [ ]:
df_array['Name'].unique()

array(['Sneha', 'Nikhil', 'Brunda', 'Badshah'], dtype=object)

In [ ]:
df_array['Name'].value_counts()
df_array['ProductName'].value_counts()

ProductName
Airpods           2
Tshirt            1
Pastel Palette    1
HP Laptop         1
Name: count, dtype: int64

In [ ]:
df_array.loc[:,'ProductName']

0            Tshirt
1           Airpods
2    Pastel Palette
3           Airpods
4         HP Laptop
Name: ProductName, dtype: object

In [ ]:
df_array.loc[:3,['Name','ProductName']]

Name     ProductName
0   Sneha          Tshirt
1  Nikhil         Airpods
2  Brunda  Pastel Palette
3  Nikhil         Airpods

In [ ]:
df_array.loc[:1,'Name':'ProductName']

Name            ID ProductName
0   Sneha           NaN      Tshirt
1  Nikhil  9.087543e+09     Airpods

In [ ]:
df_array.loc[:6,'Name':'ID']

Name            ID
0    Sneha           NaN
1   Nikhil  9.087543e+09
2   Brunda  9.087765e+09
3   Nikhil  9.087543e+09
4  Badshah  8.900065e+09

In [ ]:
df_array.loc[(df_array['ID']==9087543212) & (df_array['Name']=='Nikhil')]


Name            ID ProductName   Price
1  Nikhil  9.087543e+09     Airpods  2500.0
3  Nikhil  9.087543e+09     Airpods  2500.0

In [ ]:
df_array.loc[(df_array['ID']==9087543212) | (df_array['Name']=='Sneha')]

Name            ID ProductName   Price
0   Sneha           NaN      Tshirt  1800.0
1  Nikhil  9.087543e+09     Airpods  2500.0
3  Nikhil  9.087543e+09     Airpods  2500.0

**14.02.2025**

between()
iloc()
isin()


In [ ]:
df_array


Name            ID     ProductName    Price
0    Sneha           NaN          Tshirt   1800.0
1   Nikhil  9.087543e+09         Airpods   2500.0
2   Brunda  9.087765e+09  Pastel Palette      NaN
3   Nikhil  9.087543e+09         Airpods   2500.0
4  Badshah  8.900065e+09       HP Laptop  49000.0

In [ ]:
df_array[df_array['Price'].between(1500,2500)]
# df_array[df_array['Price'].between(1800,2500,inclusive='left')]
# df_array[df_array['Price'].between(1800,2500,inclusive='right')]
df_array[df_array['Price'].between(1800,2500,inclusive='neither')]

Empty DataFrame
Columns: [Name, ID, ProductName, Price]
Index: []

In [ ]:
df_array['Price'].isin([2000,2500,800,1800])

0     True
1     True
2    False
3     True
4    False
Name: Price, dtype: bool

In [ ]:
df_array[df_array['Price'].isin([2000,2500,800,1800])]

Name            ID ProductName   Price
0   Sneha           NaN      Tshirt  1800.0
1  Nikhil  9.087543e+09     Airpods  2500.0
3  Nikhil  9.087543e+09     Airpods  2500.0

In [ ]:
df_array['Name']

0      Sneha
1     Nikhil
2     Brunda
3     Nikhil
4    Badshah
Name: Name, dtype: object

In [ ]:
df_array.iloc[4]

Name                Badshah
ID             8900065432.0
ProductName       HP Laptop
Price               49000.0
Name: 4, dtype: object

In [ ]:
df_array.iloc[0:4,0]

#   Name
# 0	Sneha
# 1	Nikhil
# 2	Brunda
# 3	Nikhil


0     Sneha
1    Nikhil
2    Brunda
3    Nikhil
Name: Name, dtype: object

In [ ]:
df_array.iloc[2:3,0:3]
# 	Name	ID	ProductName
# 2	Brunda	9.087765e+09	Pastel Palette


Name            ID     ProductName
2  Brunda  9.087765e+09  Pastel Palette

In [ ]:
df_array['Price']=df_array['Price'].map({1800:1800,2500:2500,None:210,49000:4000})
df_array
# df_array = pandas.DataFrame([['Sneha',None,'Tshirt',1800],
#  ['Nikhil',9087543212,'Airpods',2500],['Brunda',9087764532,'Pastel Palette',None],['Nikhil',9087543212,'Airpods',2500],['Badshah',8900065432,'HP Laptop',49000]],columns=['Name','ID','ProductName','Price'])

Name            ID     ProductName   Price
0    Sneha           NaN          Tshirt  1800.0
1   Nikhil  9.087543e+09         Airpods  2500.0
2   Brunda  9.087765e+09  Pastel Palette     NaN
3   Nikhil  9.087543e+09         Airpods  2500.0
4  Badshah  8.900065e+09       HP Laptop     NaN

17.02.2025

map()

replace()

strip()

rename()


In [ ]:
dataframe = pandas.DataFrame([['Ananya M R',788,None,100],['Chanchal V',201,29100,290],['Deepal M Kapasi',289,None,299],['Tanisha Bothra',1001,279,None],['Usha V',1,211,False]])
dataframe.loc[len(dataframe)] = ['Sneha Jain M ', 200, 300, 400]
dataframe.loc[len(dataframe)]=['Nikhil Shah',1000,789,289]
dataframe


0     1        2      3
0       Ananya M R   788      NaN    100
1       Chanchal V   201  29100.0    290
2  Deepal M Kapasi   289      NaN    299
3   Tanisha Bothra  1001    279.0   None
4           Usha V     1    211.0  False
5    Sneha Jain M    200    300.0    400
6      Nikhil Shah  1000    789.0    289

In [ ]:
dataframe=dataframe.rename(columns={0:'First',1:'Second',2:'Third',3:'Fourth',4:'Fifth'})
dataframe
# First	Second	Third	Fourth	Fifth
# 0	12.0	89	200.0	728.0	False
# 1	788.0	201	289.0	1001.0
# 2	NaN	29100	NaN	279.0	211
# 3	100.0	290	299.0	NaN	23


First  Second    Third Fourth
0       Ananya M R     788      NaN    100
1       Chanchal V     201  29100.0    290
2  Deepal M Kapasi     289      NaN    299
3   Tanisha Bothra    1001    279.0   None
4           Usha V       1    211.0  False
5    Sneha Jain M      200    300.0    400
6      Nikhil Shah    1000    789.0    289

In [ ]:
# dataframe['First'].strip(' ')

# AttributeError: 'Series' object has no attribute 'strip'
dataframe['First'].str.strip(' ') #Trailing and ending

0         Ananya M R
1         Chanchal V
2    Deepal M Kapasi
3     Tanisha Bothra
4             Usha V
5       Sneha Jain M
6        Nikhil Shah
Name: First, dtype: object

In [ ]:
# dataframe['Second'].replace([1001,101],[1000,100])
dataframe['Second']=dataframe['Second'].replace(1000,101)
dataframe

First  Second    Third Fourth
0       Ananya M R     788      NaN    100
1       Chanchal V     201  29100.0    290
2  Deepal M Kapasi     289      NaN    299
3   Tanisha Bothra     101    279.0   None
4           Usha V       1    211.0  False
5    Sneha Jain M      200    300.0    400
6      Nikhil Shah     101    789.0    289

In [ ]:


# Assign a list of values directly to the 'Second' column
dataframe['Second'] = [1000, 101, 200, 1002, 2000, 278, 150]  # Ensure the length of the list matches the DataFrame length

print(dataframe)


             First  Second    Third Fourth
0       Ananya M R    1000      NaN    100
1       Chanchal V     101  29100.0    290
2  Deepal M Kapasi     200      NaN    299
3   Tanisha Bothra    1002    279.0   None
4           Usha V    2000    211.0  False
5    Sneha Jain M      278    300.0    400
6      Nikhil Shah     150    789.0    289


19.2.25

df.fillna()

df.reset_index()

df.set_index()

df.drop_duplicates()

df.bfill()

df.ffill()

df.duplicated()


In [18]:
dataframe = pandas.DataFrame([['Ananya M R',788,None,100],['Chanchal V',201,29100,290],['Deepal M Kapasi',201,None,299],['Tanisha Bothra',1001,279,None],['Usha V',1,211,False],['Ananya M R',	788,None,	100]],columns=['Names','Numb1','Numb2','Numb3'])
dataframe.loc[len(dataframe)] = ['Sneha Jain M ', 200, 300, 400]
dataframe.loc[len(dataframe)]=['Nikhil Shah',1000,789,289]
dataframe

Names  Numb1    Numb2  Numb3
0       Ananya M R    788      NaN    100
1       Chanchal V    201  29100.0    290
2  Deepal M Kapasi    201      NaN    299
3   Tanisha Bothra   1001    279.0   None
4           Usha V      1    211.0  False
5       Ananya M R    788      NaN    100
6    Sneha Jain M     200    300.0    400
7      Nikhil Shah   1000    789.0    289

In [5]:
dataframe.bfill() #from bottom

0     1        2      3
0       Ananya M R   788  29100.0    100
1       Chanchal V   201  29100.0    290
2  Deepal M Kapasi   289    279.0    299
3   Tanisha Bothra  1001    279.0  False
4           Usha V     1    211.0  False
5    Sneha Jain M    200    300.0    400
6      Nikhil Shah  1000    789.0    289

In [6]:
dataframe.ffill() # from start

0     1        2      3
0       Ananya M R   788      NaN    100
1       Chanchal V   201  29100.0    290
2  Deepal M Kapasi   289  29100.0    299
3   Tanisha Bothra  1001    279.0    299
4           Usha V     1    211.0  False
5    Sneha Jain M    200    300.0    400
6      Nikhil Shah  1000    789.0    289

In [8]:
print(dataframe.dropna())
dataframe

               0     1        2      3
1     Chanchal V   201  29100.0    290
4         Usha V     1    211.0  False
5  Sneha Jain M    200    300.0    400
6    Nikhil Shah  1000    789.0    289


0     1        2      3
0       Ananya M R   788      NaN    100
1       Chanchal V   201  29100.0    290
2  Deepal M Kapasi   289      NaN    299
3   Tanisha Bothra  1001    279.0   None
4           Usha V     1    211.0  False
5    Sneha Jain M    200    300.0    400
6      Nikhil Shah  1000    789.0    289

In [12]:
dataframe.drop_duplicates()

0     1        2      3
0       Ananya M R   788      NaN    100
1       Chanchal V   201  29100.0    290
2  Deepal M Kapasi   289      NaN    299
3   Tanisha Bothra  1001    279.0   None
4           Usha V     1    211.0  False
6    Sneha Jain M    200    300.0    400
7      Nikhil Shah  1000    789.0    289

In [13]:
dataframe.drop_duplicates(keep='last')

0     1        2      3
1       Chanchal V   201  29100.0    290
2  Deepal M Kapasi   289      NaN    299
3   Tanisha Bothra  1001    279.0   None
4           Usha V     1    211.0  False
5       Ananya M R   788      NaN    100
6    Sneha Jain M    200    300.0    400
7      Nikhil Shah  1000    789.0    289

In [14]:
dataframe.drop_duplicates(keep=False)

0     1        2      3
1       Chanchal V   201  29100.0    290
2  Deepal M Kapasi   289      NaN    299
3   Tanisha Bothra  1001    279.0   None
4           Usha V     1    211.0  False
6    Sneha Jain M    200    300.0    400
7      Nikhil Shah  1000    789.0    289

In [19]:
dataframe.drop_duplicates(['Numb1'],keep=False)

Names  Numb1  Numb2  Numb3
3  Tanisha Bothra   1001  279.0   None
4          Usha V      1  211.0  False
6   Sneha Jain M     200  300.0    400
7     Nikhil Shah   1000  789.0    289

In [20]:
dataframe.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
dtype: bool

In [21]:
dataframe.duplicated(['Names'])

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
dtype: bool

In [22]:
dataframe.duplicated(['Numb3'])

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
dtype: bool

In [23]:
dataframe.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
dtype: bool

In [30]:
dataframe.drop(['Numb3'],axis=1,inplace=True)

In [31]:
dataframe

Names  Numb1    Numb2
0       Ananya M R    788      NaN
1       Chanchal V    201  29100.0
2  Deepal M Kapasi    201      NaN
3   Tanisha Bothra   1001    279.0
4           Usha V      1    211.0
5       Ananya M R    788      NaN
6    Sneha Jain M     200    300.0
7      Nikhil Shah   1000    789.0

In [32]:
dataframe.reset_index()

index            Names  Numb1    Numb2
0      0       Ananya M R    788      NaN
1      1       Chanchal V    201  29100.0
2      2  Deepal M Kapasi    201      NaN
3      3   Tanisha Bothra   1001    279.0
4      4           Usha V      1    211.0
5      5       Ananya M R    788      NaN
6      6    Sneha Jain M     200    300.0
7      7      Nikhil Shah   1000    789.0

In [33]:
dataframe.reset_index(drop=True)

Names  Numb1    Numb2
0       Ananya M R    788      NaN
1       Chanchal V    201  29100.0
2  Deepal M Kapasi    201      NaN
3   Tanisha Bothra   1001    279.0
4           Usha V      1    211.0
5       Ananya M R    788      NaN
6    Sneha Jain M     200    300.0
7      Nikhil Shah   1000    789.0

In [35]:
dataframe.set_index('Names',inplace=True) #column

In [38]:
dataframe.loc['Ananya M R']

Numb1  Numb2
Names                   
Ananya M R    788    NaN
Ananya M R    788    NaN

In [53]:
dataframe.loc['Deepal M Kapasi':,'Numb2':]

Numb2
Names                 
Deepal M Kapasi    NaN
Tanisha Bothra   279.0
Usha V           211.0
Ananya M R         NaN
Sneha Jain M     300.0
Nikhil Shah      789.0